addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.0")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "0.14.6")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "1.5.1")
addSbtPlugin("org.scoverage"    % "sbt-coveralls"       % "1.2.2")
addSbtPlugin("com.lucidchart"   % "sbt-scalafmt"        % "1.15")
